name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout del código fuente
      - uses: actions/checkout@v3

      # 2. Configuración de Node.js
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias del proyecto
      - name: Install Dependencies
        run: npm ci

      # 4. Build del proyecto NestJS
      - name: Build NestJS Project
        run: npm run build

      # 5. Empaquetar el proyecto para Lambda
      - name: Create Deployment Package
        run: |
          mkdir -p dist
          cp -r node_modules dist/
          cp -r ./package.json dist/
          cd dist
          zip -r code.zip .
      # 6. Desplegar la función Lambda con AWS CLI
      - name: Deploy Lambda using AWS CLI
        run: |
          docker run \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_DEFAULT_REGION="us-east-2" \
            -v $(pwd):/workspace \
            -w /workspace \
            amazon/aws-cli:2.15.2 \
            lambda update-function-code \
            --function-name arn:aws:lambda:us-east-2:890742573549:function:cardenascode-starwars-api-production-api \
            --zip-file fileb://dist/code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"


